packages:
  - packages/*
  - WebServer
  - NativeApp

onlyBuiltDependencies:
  - '@prisma/engines'
  - better-sqlite3
  - electron
  - esbuild
  - lzma-native
  - prisma
  - rclone.js
  - sharp
  - unrs-resolver
