// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";
import { getPrismaDatabaseUrl } from "./electron/databasePath";

export default defineConfig({
  schema: "node_modules/@rtc-database/shared/prisma/schema.prisma",
  migrations: {
    path: "node_modules/@rtc-database/shared/prisma/migrations",
  },
  datasource: {
    url: getPrismaDatabaseUrl(),
  },
});
