import type { Metadata } from "next";
<<<<<<< HEAD
import { Geist, Geist_Mono } from "next/font/google";

=======
import { Montserrat } from "next/font/google";

import Footer from "./components/Footer";
>>>>>>> 3934de0 (font)
import PopupProvider from "./components/Popup/PopupProvider";
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <PopupProvider>{children}</PopupProvider>
=======
      <body className={`${montserrat.variable} font-sans antialiased`}>
        <PopupProvider>
          {children}
          <Footer />
        </PopupProvider>
>>>>>>> 3934de0 (font)
      </body>
    </html>
  );
}
